MariaDB/mariadb.org-tools

- buildbot/maria-master.cfg
To be built on newly added macos-10-13 builder. Currently my slave is only used for kvm-sched-mainonly-10.0+ by the looks of it. Example branch:
https://github.com/shinnok/server/commits/tm-10.3-macfixes
https://buildbot.askmonty.org/buildbot/buildslaves/shinnok-bld
> Add scheduler for personal GH tm-* branches

- buildbot.mariadb.org/util/nginx.conf
After testing with siege : `siege -v -r 4 -c 5 buildbot.mariadb.org` have seen that there is no rate limiting.
This patch is adding a rate limiting  to buildbot.mariadb.org. 
@shinnok  please review and let me know should the same be added to ci.mariadb.org.
> Add rate limiting

- buildbot.mariadb.org/util/nginx.conf
In order to be consistent with proxy path `/`character is added at the
end of proxy path.
Instead nginx assumes original request path.
> Add trailing slash in proxy path

- buildbot.mariadb.org/dockerfiles/centos-7.dockerfile
- buildbot.mariadb.org/dockerfiles/debian-9.dockerfile
- buildbot.mariadb.org/dockerfiles/fedora-28.dockerfile
- buildbot.mariadb.org/dockerfiles/opensuse-15.dockerfile
- buildbot.mariadb.org/dockerfiles/opensuse-42.dockerfile
- buildbot.mariadb.org/dockerfiles/ubuntu-1404.dockerfile
- buildbot.mariadb.org/dockerfiles/ubuntu-1604.dockerfile
- buildbot.mariadb.org/dockerfiles/ubuntu-1804.dockerfile
- Remove deprecated `MAINTAINER` keyword, add `LABEL` instead (all distros)
- Remove the `USER root` it is by default (all distros)
- Decrease number of layers and generated commits created by `RUN` command
(for debian, ubuntu based distros, other distros have piped layers)
@shinnok  please review
> Minor changes in docker files

- monitoring/mirmon/README.md
- monitoring/mirmon/webhook/mirmon_update.sh
- monitoring/mirmon/webhook/webhook.yaml
Once the webhook is configured on the upstream repo, on every merge, the monitoring/mirmon/mariadb_mirror_list is deployed on mirmon.mariadb.org and mirmon will start immediatelly an update of the status page.
Based on:
- https://github.com/adnanh/webhook
- https://www.digitalocean.com/community/tutorials/deploying-react-applications-with-webhooks-and-slack-on-ubuntu-16-04
> Adding webhooks to mirmon

- faust/tools/get_subtitles
This script permits to extract autogenerated subtitles from YouTube and remove timestamps.
> Add a script to extract subtitles from YouTube

- release/prep
Hey @dbart,
Is this ok?
update_the_docker_library_mariadb_version only needs to be run once for all the releases of the day.
> update prep script for docker library/mariadb releases

- buildbot.mariadb.org/master.cfg
From failure: https://buildbot.mariadb.org/#/builders/198/builds/704/steps/2/logs/stdio
Don't error like:
+ galera_path=/usr/lib64/galera-4/libgalera_smm.so
+ mysql -uroot -e 'set global wsrep_provider="/usr/lib64/galera-4/libgalera_smm.so"; show status like "wsrep%"'
ERROR 1238 (HY000) at line 1: Variable 'wsrep_provider' is a read only variable
program finished with exit code 1
MariaDB won't read a [galera] section if not enabled. Following
instructions start the galera service.
Use journalctl to show the mariadb.service only
Remove old 5.5-galera, 10.0-galera code
> bb.org: wsrep_provider is read-only

- buildbot.mariadb.org/dockerfiles/centos-7.dockerfile
- buildbot.mariadb.org/dockerfiles/fedora-33.dockerfile
- buildbot.mariadb.org/dockerfiles/fedora-34.dockerfile
- buildbot.mariadb.org/dockerfiles/rhel-8.dockerfile
- buildbot.mariadb.org/dockerfiles/sles-15.dockerfile
provided by epel. needed amd64 only
sles-15 verified by https://distrowatch.com/table.php?distribution=sle&pkglist=true&version=15-sp2 and it not being on the mirror https://archive.mariadb.org/mariadb-10.4.20/yum/sles15-amd64/rpms/.
> bb.org: jemalloc-devel for rpm builders for 10.2-10.4 tokudb

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/centos.Dockerfile
- buildbot.mariadb.org/ci_build_images/centos7.Dockerfile
- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
- buildbot.mariadb.org/ci_build_images/fedora.Dockerfile
- buildbot.mariadb.org/ci_build_images/rhel7.Dockerfile
- buildbot.mariadb.org/ci_build_images/rhel8.Dockerfile
The last thing we want is for us to have a typo in the CI yml and have
fedora:34 images when we think we should have fedora 35 and everything
be green.
> Using a default base image is not recommended

- .github/workflows/bb_containers.yml
Add Fedora 35 to CI image creation.
@fauust Am I missing something or is it that simple?
> bb.org: Add Fedora 35 to BB worker image CI

- buildbot.mariadb.org/master-galera/master.cfg
- buildbot.mariadb.org/master.cfg
- buildbot/maria-master.cfg
- release/mkrepo-debian.sh
- release/mkrepo-ubuntu.sh
This copies of the Foundations construction of the deb repository. With this layout the repo file of the following can be used:
deb [trusted=yes] http://hasky.askmonty.org/archive/10.6/build-44208/kvm-deb-impish-amd64/debs/ ./
This can be also used for the debuginfo packages.
I've attempted to include all the locations where the paths of /binary are expected.
> bb: produce debian repo compatible file structure

- buildbot.mariadb.org/ci_build_images/centos7.Dockerfile
gnutls is missing for the aarch64-centos-7-bintar-* builders as shown in https://buildbot.mariadb.org/#/builders/248/builds/2678. Add the missing dependency to solve this issue.
> bb.org: Add gnutls-devel dependency to fix aarch64-centos-7-bintar-*

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
This permits to build 10.7 on the following OS version (previously only targeting 10.5):
- Debian 9
- Debian 10
- Ubuntu 18.04
- Ubuntu 20.04
For some old OS version, some dependencies are not available and should be skipped.
> Build 10.7 on older Debian versions

- .github/workflows/bb_containers.yml
On Debian 9 ARM, the buildbot worker fails to start with, see
https://jira.mariadb.org/browse/MDBF-329/.
This new check covers also other plaforms and should permit us to detect
any buildbot worker problem before pushing to the registry.
> Improve container testing

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/common.Dockerfile
Fix a python dependency on Debian 9
twisted[tls] can't be installed on Debian 9 (ARM) without the `incremental` packages,
and somehow, it is not installed automatically.
See: https://jira.mariadb.org/browse/MDBF-329
+ disable Centos8:
See: https://forums.centos.org/viewtopic.php?f=54&t=78708
> Fix MDBF-329

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
See: https://jira.mariadb.org/browse/MDBF-330
+ adding double comments to be sure we do not accidentally uncomment OS we do not want to build.
> Add missing dependency for Debian sid

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
See: https://jira.mariadb.org/browse/MDBF-346
> libzstd-dev (>= 1.1.3) is needed on Debian9

- .github/workflows/bb_containers.yml
Seems to not need any exclusions from dependencies
Will look at bb config once workers are added.
> MDBF-349: Add Ubuntu 22.04 for ci_workers

- .github/workflows/bb_containers.yml
- buildbot.mariadb.org/ci_build_images/common.Dockerfile
For centos7 (ppc64le), it's necessary to install specific pip packages versions.
See:
https://jira.mariadb.org/browse/MDBF-273?focusedCommentId=216315
> Fix centos:7 ppc64le pip problem

- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
a) don't include backports now that we've fixed the autobake
b) temporarily hack in libfmt so we don't break CI merging https://github.com/MariaDB/server/pull/2062
> bb.org: debian ci worker container changes

- release/prep
To keep the docker library master branch as something
that can be built with existing releases, and the next
branch having feature that are from the next server version,
releases have to be done from the next branch.
> release: docker library from next branch

- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
gnutls is needed to prevent failures such as
https://buildbot.mariadb.org/#/builders/242/builds/5267.
> bb.org: Add gnutls for Debian 9 images

- buildbot.mariadb.org/ci_build_images/rhel7.Dockerfile
Also, cmake was not installed correctly for ppcle64.
To be sure that we do not use the old cmake version, we remove it also
(was installed with @development package)
> Cmake > 3.10 is available on epel repo

- buildbot.mariadb.org/utils.py
Here is the formula:
```console
10*last(//system.cpu.util[,iowait])+last(//system.cpu.load[all,avg1])
```
> Use another calculated metric from Zabbix

- buildbot.mariadb.org/ci_build_images/rhel7.Dockerfile
pcre2-devel is needed in order to solve the following build issues:
CMake Error at cmake/pcre.cmake:83 (MESSAGE):
system pcre2-8 library is not found or unusable
as shown in https://buildbot.mariadb.org/#/builders/162/builds/8625
> bb.org: Add pcre2-devel for RHEL 7

- buildbot/maria-master.cfg
- buildbot/steps/minor_upgrade.deb.sh
With MDEV-27033, 10.9 mariadb Packages only contain Source: mariadb
Mirrors 727b92f500d84bfbedb20ad2a52a75b96977bbad change I did which [seems to have worked](https://buildbot.mariadb.org/#/builders/367/builds/218).
> bb.corp: deb maj/min install/upgrade 10.9 versionless

- buildbot.mariadb.org/ci_build_images/README.md
Add tagging to 'manually build containers' instructions so it'll easier to use builded images
> MDBF-404: Add tagging to README.md

- buildbot.mariadb.org/ci_build_images/debian.Dockerfile
Fix Python Cryptography building proble with adding `ENV CARGO_NET_GIT_FETCH_WITH_CLI=true` to Debian common Docker file. It fixes Ubuntu 20.04-22.04 building and does not do any harm to Debian or older Ubuntu image building
> MDBF-410: Fix building of Ubuntu 20.04-22.04 Docker images

- release/prep
Because we don't want to be Naughty (from the official images test
(https://github.com/docker-library/official-images/runs/6542938100?check_suite_focus=true),
Our commits need to be in the master branch, so we merge origin/next
back to master now that the release is done.
Since the rests of these steps are in one hit, we can do all the
releases and test in one commit too.
> update Docker Library Release

- buildbot.mariadb.org/scripts/docker-library-build-and-test.sh
@grooverdan how could I test my changes without merging, do you want me to add the same logic as for install/upgrade script (see: https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/scripts/bash_lib.sh#L28).
One suggested approach is that we know that https://buildbot.mariadb.org/#/builders/311/builds/9150 does not clean the environment. So I could compare 2 run (one before the patch and the one after).
> fix MDBF-414

- buildbot/maria-master.cfg
- buildbot/steps/mtr.deb.sh
Prepare for the move using /usr/share/mariadb* if /usr/share/mysql* fails.
server change: https://github.com/MariaDB/server/pull/2392
> MDEV-30205 move /usr/share/mysql* to /usr/share/mariadb*
